### PR TITLE
Spanish Translation

### PR DESCRIPTION
**Pull request by sguinetti**
Greetings. This pull request takes the Spanish translation of the application to make it suitable for the Spanish-speaking audience.

### CODE REVIEW

**Review by rosuH — COMMENTED** [review]
Thanks for your PR. Everything looks good for now🍺 . But I had modified some UI and `string.xml` in `dev` branch XD which may need you to enhance your translation. 

I would release a new version this weekend, so this PR would not merge until the new version's code merge into master.

When I am ready, I would mention you. Thanks again.

**Comment by rosuH** [comment]
@sguinetti Hi, the new version has been released. Please create a PR base on that. Thanks~

**Comment by sguinetti** [comment]
Updated: #22

**Comment by workfilemmfloe** [comment]
Update #22

**Pull request closed without merging**
